### ISSUE TITLE
老哥，请教下

### ISSUE THREAD

**Issue by skyezu** [g1335333249/jd-cloud-monitor#2]
我是小白，启动的时候
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-12-06 16:34:52.899 ERROR 16732 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'aliyunDnsTask': Invocation of init method failed; nested exception is java.lang.NullPointerException
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:422) ~[spring-beans-5.3.8.jar!/:5.3.8]

上述报错，怎么回事

还是配置文件中

jdcloudwifiapp下面的四项
accessKey
macKey
tgt
pin

怎么获取，谢谢。

**Comment by skyezu** [comment]
> 我是小白，启动的时候 Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled. 2021-12-06 16:34:52.899 ERROR 16732 --- [ main] o.s.boot.SpringApplication : Application run failed
> 
> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'aliyunDnsTask': Invocation of init method failed; nested exception is java.lang.NullPointerException at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160) ~[spring-beans-5.3.8.jar!/:5.3.8] at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:422) ~[spring-beans-5.3.8.jar!/:5.3.8]
> 
> 上述报错，怎么回事
> 
> 还是配置文件中
> 
> jdcloudwifiapp下面的四项 accessKey macKey tgt pin
> 
> 怎么获取，谢谢。
